name: DQN
dependencies:
    - python>=3.7
    - pip
    - pip:
        - torch>=1.3.1
        - tqdm>=4.35.0
        - pandas>=0.24.2
        - numpy
        - gym==0.19.0
        - pygame 
        - msgpack
        - msgpack-numpy 
        - opencv-python
        - pyglet==1.2.4